# Creating and accessing matrices in NumPy

In [2]:
import sympy as sym
import numpy as np
from IPython.display import display, Math 

In [3]:
A = [ [1,2], [3,4] ]

In [4]:
A

[[1, 2], [3, 4]]

In [5]:
type(A)

list

### Creating a matrix with NumPy

In [6]:
A = np.array([ [1,2], [3,4] ])

In [7]:
type(A)

numpy.ndarray

In [8]:
print(A)

[[1 2]
 [3 4]]


In [9]:
display(Math(sym.latex(sym.sympify(A))))

<IPython.core.display.Math object>

### Empty arrays

In [10]:
np.zeros([4,6])

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
mat = np.zeros([4,6])

In [12]:
mat[0,1] = 2

In [13]:
mat

array([[0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
mat[2, 4] = 7

In [15]:
mat

array([[0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 7., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
display(Math(sym.latex(sym.sympify(mat))))

<IPython.core.display.Math object>

### Looping through matrices

In [17]:
numrange = range(0,2)

for row_i in numrange:
    for col_i in numrange:
        mat[row_i, col_i] = (-1) ** (row_i + col_i)
        
mat
    

array([[ 1., -1.,  0.,  0.,  0.,  0.],
       [-1.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  7.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [18]:
numrange = range(0,4)

for row_i in numrange:
    for col_i in numrange:
        mat[row_i, col_i] = (-1) ** (row_i + col_i)
        
mat
    

array([[ 1., -1.,  1., -1.,  0.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.],
       [ 1., -1.,  1., -1.,  7.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.]])

### Exercise

In [19]:
from sympy.abc import x
from sympy.abc import y


Fxy = (4 + x)*(2 - y)
Fxy.subs({x:1, y:0})
numrange = range(0,3)

mat = np.zeros([3,3])

for xi in numrange:
    for yi in numrange:
        mat[xi, yi] = Fxy.subs({x:xi, y:yi})
        
mat

array([[ 8.,  4.,  0.],
       [10.,  5.,  0.],
       [12.,  6.,  0.]])

In [20]:
display(Math(sym.latex(sym.sympify(mat))))

<IPython.core.display.Math object>

### Exercise_2

In [44]:
nums = range(1,11)

mat_mult = np.zeros((len(nums), len(nums)),dtype=int)

for rowi in nums:
    for coli in nums:
        mat_mult[rowi-1,coli-1] = rowi*coli
    
mat_mult

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [45]:
display(Math(sym.latex(sym.sympify(mat_mult))))

<IPython.core.display.Math object>